#!/usr/bin/env node
// Builds dist/ from src/. No dependencies: Node 18+ only.
//   dist/tokens.css          CSS custom properties (dark default, light via [data-theme] or OS preference)
//   dist/tokens.ts           Typed, resolved values for JS/TS consumers
//   dist/tokens.json         Flat resolved map for tooling
//   dist/tailwind-preset.cjs Tailwind preset wired to the CSS variables

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const PREFIX = 'elx';
const read = (p) => JSON.parse(readFileSync(new URL(p, import.meta.url), 'utf8'));
const core = read('../src/core.json');
const themes = { dark: read('../src/themes/dark.json'), light: read('../src/themes/light.json') };

// ---------- flatten DTCG tree into [{ path, value, type, description }] ----------
function flatten(tree, path = [], inheritedType, out = []) {
  const type = tree.$type ?? inheritedType;
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith('$') || node === null || typeof node !== 'object') continue;
    if ('$value' in node) {
      out.push({
        path: [...path, key].join('.'),
        value: node.$value,
        type: node.$type ?? type,
        description: node.$description,
      });
    } else {
      flatten(node, [...path, key], type, out);
    }
  }
  return out;
}

const REF = /\{([^}]+)\}/g;
const cssName = (path) => `--${PREFIX}-${path.replace(/\./g, '-')}`;

const coreTokens = flatten(core);
const themeTokens = Object.fromEntries(Object.entries(themes).map(([n, t]) => [n, flatten(t)]));

// ---------- validation ----------
const errors = [];

const lookupFor = (theme) =>
  new Map([...coreTokens, ...themeTokens[theme]].map((t) => [t.path, t]));

for (const theme of Object.keys(themes)) {
  const lookup = lookupFor(theme);
  for (const t of [...coreTokens, ...themeTokens[theme]]) {
    if (typeof t.value !== 'string') continue;
    for (const [, ref] of t.value.matchAll(REF)) {
      if (!lookup.has(ref)) errors.push(`[${theme}] ${t.path} references missing token {${ref}}`);
    }
  }
}

// dark and light must define the same semantic keys
const darkKeys = new Set(themeTokens.dark.map((t) => t.path));
const lightKeys = new Set(themeTokens.light.map((t) => t.path));
for (const k of darkKeys) if (!lightKeys.has(k)) errors.push(`light theme is missing ${k}`);
for (const k of lightKeys) if (!darkKeys.has(k)) errors.push(`dark theme is missing ${k}`);

// components must not reach for raw palette values inside theme files
for (const [theme, list] of Object.entries(themeTokens)) {
  for (const t of list) {
    if (t.path.startsWith('palette.')) errors.push(`[${theme}] ${t.path}: palettes belong in core.json`);
  }
}

if (errors.length) {
  console.error('Token build failed:\n  ' + errors.join('\n  '));
  process.exit(1);
}

// ---------- resolution ----------
function resolve(value, lookup, trail = []) {
  if (typeof value !== 'string') return value;
  return value.replace(REF, (_, ref) => {
    if (trail.includes(ref)) throw new Error(`Circular reference: ${[...trail, ref].join(' -> ')}`);
    return String(resolve(lookup.get(ref).value, lookup, [...trail, ref]));
  });
}
const toVar = (value) =>
  typeof value === 'string' ? value.replace(REF, (_, ref) => `var(${cssName(ref)})`) : value;

// ---------- CSS ----------
const decl = (t) => `  ${cssName(t.path)}: ${toVar(t.value)};${t.description ? ` /* ${t.description.replace(/\*\//g, '')} */` : ''}`;
const bare = (t) => `  ${cssName(t.path)}: ${toVar(t.value)};`;

// Group core tokens by their first path segment for readable output
const groups = new Map();
for (const t of coreTokens) {
  const g = t.path.split('.')[0];
  if (!groups.has(g)) groups.set(g, []);
  groups.get(g).push(t);
}

const coreBlock = [...groups.entries()]
  .map(([g, list]) => `  /* ${g} */\n${list.map(bare).join('\n')}`)
  .join('\n\n');

const darkBlock = themeTokens.dark.map(decl).join('\n');
const lightBlock = themeTokens.light.map(bare).join('\n');
const indent = (s) => s.split('\n').map((l) => '  ' + l).join('\n');

const css = `/* GENERATED by scripts/build.mjs. Do not edit; change src/ and run \`pnpm build\`. */

:root {
  color-scheme: dark;

${coreBlock}

  /* semantic color: dark (default) */
${darkBlock}
}

/* Explicit opt-in to light */
:root[data-theme='light'] {
  color-scheme: light;
${lightBlock}
}

/* Follow the OS only when the page has not chosen a theme */
@media (prefers-color-scheme: light) {
  :root:not([data-theme='dark']) {
    color-scheme: light;
${indent(lightBlock)}
  }
}

/* Honour reduced-motion: collapse durations so transitions become instant */
@media (prefers-reduced-motion: reduce) {
  :root {
    --${PREFIX}-motion-duration-instant: 0ms;
    --${PREFIX}-motion-duration-fast: 0ms;
    --${PREFIX}-motion-duration-base: 0ms;
    --${PREFIX}-motion-duration-slow: 0ms;
  }
}
`;

// ---------- TS + JSON ----------
function nest(entries) {
  const root = {};
  for (const [path, value] of entries) {
    const keys = path.split('.');
    let node = root;
    keys.slice(0, -1).forEach((k) => (node = node[k] ??= {}));
    node[keys.at(-1)] = value;
  }
  return root;
}

const resolvedCore = coreTokens.map((t) => [t.path, resolve(t.value, lookupFor('dark'))]);
const resolvedThemes = Object.fromEntries(
  Object.keys(themes).map((n) => [
    n,
    themeTokens[n].map((t) => [t.path, resolve(t.value, lookupFor(n))]),
  ]),
);

const coreObj = nest(resolvedCore);
const themeObjs = Object.fromEntries(Object.entries(resolvedThemes).map(([n, e]) => [n, nest(e)]));
const varMap = Object.fromEntries(
  [...coreTokens, ...themeTokens.dark].map((t) => [t.path, `var(${cssName(t.path)})`]),
);

const ts = `// GENERATED by scripts/build.mjs. Do not edit.

export const core = ${JSON.stringify(coreObj, null, 2)} as const;

export const themes = ${JSON.stringify(themeObjs, null, 2)} as const;

/** CSS variable reference for every token path, e.g. cssVar['color.bg.base'] -> 'var(--${PREFIX}-color-bg-base)' */
export const cssVar = ${JSON.stringify(varMap, null, 2)} as const;

export type ThemeName = keyof typeof themes;
export type TokenPath = keyof typeof cssVar;
`;

const flat = {
  core: Object.fromEntries(resolvedCore),
  themes: Object.fromEntries(Object.entries(resolvedThemes).map(([n, e]) => [n, Object.fromEntries(e)])),
};

// ---------- Tailwind preset ----------
const v = (path) => `var(${cssName(path)})`;
const sub = (prefix) =>
  Object.fromEntries(
    coreTokens
      .filter((t) => t.path.startsWith(prefix + '.'))
      .map((t) => [t.path.slice(prefix.length + 1), v(t.path)]),
  );

const semanticColors = nest(themeTokens.dark.map((t) => [t.path.replace(/^color\./, ''), v(t.path)]));
const paletteColors = {};
for (const t of coreTokens.filter((t) => t.path.startsWith('palette.'))) {
  const [, scale, step] = t.path.split('.');
  (paletteColors[scale] ??= {})[step] = v(t.path);
}

const preset = {
  theme: {
    extend: {
      colors: { ...semanticColors, palette: paletteColors },
      fontFamily: Object.fromEntries(
        coreTokens.filter((t) => t.path.startsWith('font.family.')).map((t) => [t.path.split('.').pop(), [v(t.path)]]),
      ),
      fontSize: sub('font.size'),
      fontWeight: sub('font.weight'),
      lineHeight: sub('font.leading'),
      letterSpacing: sub('font.tracking'),
      spacing: sub('space'),
      borderRadius: sub('radius'),
      boxShadow: sub('shadow'),
      maxWidth: { prose: v('measure.prose'), ui: v('measure.ui'), page: v('measure.page') },
      transitionDuration: sub('motion.duration'),
      transitionTimingFunction: sub('motion.easing'),
      zIndex: sub('z'),
      screens: Object.fromEntries(
        coreTokens.filter((t) => t.path.startsWith('breakpoint.')).map((t) => [t.path.split('.').pop(), resolve(t.value, lookupFor('dark'))]),
      ),
    },
  },
};

const tailwind = `// GENERATED by scripts/build.mjs. Do not edit.
// Usage in tailwind.config.js:  presets: [require('@elenchus-protocol/tokens/tailwind')]
// Remember to import '@elenchus-protocol/tokens/css' once in your app entry.
module.exports = ${JSON.stringify(preset, null, 2)};
`;

// ---------- write ----------
mkdirSync(new URL('../dist/', import.meta.url), { recursive: true });
const out = (name, data) => writeFileSync(new URL(`../dist/${name}`, import.meta.url), data);
out('tokens.css', css);
out('tokens.ts', ts);
out('tokens.json', JSON.stringify(flat, null, 2) + '\n');
out('tailwind-preset.cjs', tailwind);

const count = coreTokens.length + themeTokens.dark.length;
console.log(`Built ${count} tokens (${coreTokens.length} core + ${themeTokens.dark.length} semantic x ${Object.keys(themes).length} themes).`);
